<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Course
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <video width="100%" controls id="video">
                    <source src="video.mp4" type="video/mp4">
                    <source src="video.ogg" type="video/ogg">
                    Your browser does not support HTML video.
                </video>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro dolorum recusandae sapiente ipsum iste nesciunt, architecto eum! Voluptates nam impedit vitae obcaecati ipsum ut ipsam adipisci veniam dignissimos quasi quis dolores, sint aperiam, excepturi cum natus voluptate iste repellat. Porro accusamus, officiis iste quam adipisci, nam temporibus atque ut odit sit nesciunt quod tempora ducimus distinctio provident laudantium aliquam nisi expedita aspernatur! Ut quae aliquid fugit odit ipsum delectus quisquam quas debitis hic culpa qui in reiciendis a autem ipsam, labore, ducimus officiis illo veritatis inventore excepturi magnam corporis! Maxime quos vero cupiditate, vel facilis temporibus voluptas sequi quo, error aspernatur rem consequatur molestiae quas soluta. Voluptas velit aliquam deleniti voluptatem illo tempora ipsam quibusdam ex dicta eaque ipsum quisquam, porro fugit qui laboriosam optio, omnis sit labore ducimus vel amet rerum nostrum et. Voluptatibus eos labore quidem architecto voluptate, quas repellat incidunt, eum exercitationem corrupti, voluptatum aut at ea culpa ipsum dolore consequatur rerum unde velit libero? Suscipit in praesentium harum ab quod ipsam tenetur molestiae eius laudantium aperiam necessitatibus ullam dicta provident tempora molestias laborum unde cum nesciunt qui cumque, rem, exercitationem dolores vero delectus. Obcaecati hic, vel, facilis vitae nostrum ad harum debitis sint atque quisquam voluptatem.</p>
            <br>
            <br>
            <button id="finish-button" style="border: 1px solid gray; padding: 5px 10px">Finish</button>
        </div>
    </div>

    <script>
        document.getElementById('video').addEventListener('ended', function(e) {
            console.log('done watching');
        });

        // document.getElementById('video').addEventListener('touchmove', function(event) {                                                                                                                                                                                                               
        //     // Prevent scrolling on this element                                                                                                                                                                                                                              
        //     // event.preventDefault();                                                                                                                                                                                                                                           
        // }, false); 

        // function isInViewport(el) {
        //     const rect = el.getBoundingClientRect();
        //     return (
        //         rect.top >= 0 &&
        //         rect.left >= 0 &&
        //         rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
        //         rect.right <= (window.innerWidth || document.documentElement.clientWidth)

        //     );
        // }


        // const box = document.getElementById('finish-button');

        // document.addEventListener('scroll', function () {
        //     const messageText = isInViewport(box) ?
        //         'The button is visible in the viewport' :
        //         'The button is not visible in the viewport';

        //     if (isInViewport(box)) {
        //         alert('Finished reading!');
        //     }

        //     // console.log(messageText);

        // }, {
        //     passive: true
        // });
    </script>
</x-app-layout>
